const cfg=window.HASTREITER_CONFIG||{supabaseUrl:"https://wjxppqxudiomfgfbeyav.supabase.co",supabaseAnonKey:"sb_publishable_vSd_ftJq3_fNylpQ6pbVSQ_r7XChVQP",adminEmail:"hastreiter-dienstleistungen@gmx.de"};
let sb=null,dataCache={income:[],expense:[],orders:[],requests:[],appointments:[],cleaning:[],receipts:[]},currentReceiptFile=null;
const euro=n=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n||0));
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const setText=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v;};
function showSection(id){document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));document.getElementById(id)?.classList.add("active");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.section===id));const t={dashboard:"Dashboard",anfragen:"Anfragen",einnahmen:"Einnahmen",ausgaben:"Ausgaben",belege:"Belege",auftraege:"Aufträge",reinigung:"Reinigung",kalender:"Kalender",auswertungen:"Auswertungen"};setText("pageTitle",t[id]||"Hastreiter");document.querySelector(".sidebar")?.classList.remove("open");}
document.querySelectorAll("[data-section]").forEach(b=>b.addEventListener("click",()=>showSection(b.dataset.section)));
document.querySelectorAll("[data-section-link]").forEach(b=>b.addEventListener("click",()=>showSection(b.dataset.sectionLink)));
document.getElementById("menuBtn")?.addEventListener("click",()=>document.querySelector(".sidebar")?.classList.toggle("open"));
function setConnectionError(a,b){setText("connectionStatus",a);const e=document.getElementById("loginError");if(e)e.textContent=b;}
async function init(){if(!window.supabase){setConnectionError("Supabase-Bibliothek nicht geladen","Bitte Seite neu laden.");return;}if(!cfg.supabaseUrl||!cfg.supabaseAnonKey){setConnectionError("Supabase-Konfiguration fehlt","Die Supabase-Konfiguration wurde nicht geladen.");return;}sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);const{data:{session}}=await sb.auth.getSession();if(session)enterApp();else document.getElementById("loginScreen")?.classList.remove("hidden");sb.auth.onAuthStateChange((_e,s)=>{if(s)enterApp();});}
async function login(e){e.preventDefault();const email=document.getElementById("loginEmail").value.trim().toLowerCase(),password=document.getElementById("loginPassword").value,err=document.getElementById("loginError");err.textContent="";if(email!==String(cfg.adminEmail||"").toLowerCase()){err.textContent="Diese E-Mail ist nicht freigeschaltet.";return;}if(!sb){err.textContent="Supabase ist noch nicht verbunden.";return;}const{error}=await sb.auth.signInWithPassword({email,password});if(error)err.textContent=error.message;}
document.getElementById("loginForm")?.addEventListener("submit",login);
async function enterApp(){document.getElementById("loginScreen")?.classList.add("hidden");document.getElementById("app")?.classList.remove("hidden");setText("connectionStatus","Verbunden");await loadData();}
document.getElementById("logoutBtn")?.addEventListener("click",async()=>{if(sb)await sb.auth.signOut();location.reload();});
async function loadData(){if(!sb)return;const r=await Promise.all([sb.from("einnahmen").select("*").order("datum",{ascending:false}),sb.from("ausgaben").select("*").order("datum",{ascending:false}),sb.from("auftraege").select("*").order("startdatum",{ascending:true}),sb.from("anfragen").select("*").order("erstellt_am",{ascending:false}),sb.from("termine").select("*").order("datum",{ascending:true}).limit(10),sb.from("reinigungsauftraege").select("*").order("datum",{ascending:true}),sb.from("belege").select("*").order("erstellt_am",{ascending:false})]);dataCache={income:r[0].data||[],expense:r[1].data||[],orders:r[2].data||[],requests:r[3].data||[],appointments:r[4].data||[],cleaning:r[5].data||[],receipts:r[6].data||[]};render();}
function list(id,a,f){const e=document.getElementById(id);if(!e)return;e.innerHTML=a.length?a.slice(0,100).map(x=>`<div class="list-row">${f(x)}</div>`).join(""):"<div class='empty'>Keine Einträge vorhanden.</div>";}
function render(){const m=new Date().toISOString().slice(0,7),mi=dataCache.income.filter(x=>String(x.datum||"").slice(0,7)===m).reduce((s,x)=>s+Number(x.betrag??x.brutto??0),0),me=dataCache.expense.filter(x=>String(x.datum||"").slice(0,7)===m).reduce((s,x)=>s+Number(x.betrag??x.brutto??0),0);setText("statIncome",euro(mi));setText("statExpense",euro(me));setText("statOrders",dataCache.orders.filter(x=>!["Erledigt","Storniert"].includes(x.status)).length);const nr=dataCache.requests.filter(x=>(x.status||"Neu")==="Neu").length;setText("statRequests",nr);setText("requestBadge",nr);const ti=dataCache.income.reduce((s,x)=>s+Number(x.betrag??x.brutto??0),0),te=dataCache.expense.reduce((s,x)=>s+Number(x.betrag??x.brutto??0),0);setText("totalIncome",euro(ti));setText("totalExpense",euro(te));setText("totalResult",euro(ti-te));list("incomeList",dataCache.income,x=>`${esc(x.datum||"")} – ${esc(x.beschreibung||"Einnahme")} – <strong>${euro(x.betrag??x.brutto)}</strong>`);list("expenseList",dataCache.expense,x=>`${esc(x.datum||"")} – ${esc(x.beschreibung||"Ausgabe")} – <strong>${euro(x.betrag??x.brutto)}</strong>`);list("receiptList",dataCache.receipts,x=>`${esc(x.datum||"")} – ${esc(x.lieferant||x.beschreibung||"Beleg")} – <strong>${euro(x.brutto??x.betrag)}</strong>`);list("requestsList",dataCache.requests,x=>`${esc(x.erstellt_am||x.datum||"")} – ${esc(x.name||x.kunde||"Anfrage")} – ${esc(x.status||"Neu")}`);list("ordersList",dataCache.orders,x=>`${esc(x.startdatum||"")} – ${esc(x.titel||x.beschreibung||"Auftrag")} – ${esc(x.status||"")}`);list("cleaningList",dataCache.cleaning,x=>`${esc(x.datum||"")} – ${esc(x.kunde||x.name||"Reinigung")}`);list("calendarList",dataCache.appointments,x=>`${esc(x.datum||"")} ${esc(x.uhrzeit||"")} – ${esc(x.titel||x.beschreibung||"Termin")}`);list("nextAppointments",dataCache.appointments,x=>`${esc(x.datum||"")} ${esc(x.uhrzeit||"")} – ${esc(x.titel||x.beschreibung||"Termin")}`);}
function reviewFile(f){currentReceiptFile=f;document.getElementById("receiptReview")?.classList.remove("hidden");setText("receiptPreviewName",`Datei: ${f.name}`);setText("receiptUploadStatus","Datei übernommen. Bitte erkannte/erfasste Daten prüfen.");const i=document.getElementById("receiptImagePreview");if(i&&f.type.startsWith("image/")){i.src=URL.createObjectURL(f);i.hidden=false;}else if(i)i.hidden=true;}
document.getElementById("takeReceiptBtn")?.addEventListener("click",()=>document.getElementById("receiptCameraInput")?.click());
document.getElementById("uploadReceiptBtn")?.addEventListener("click",()=>document.getElementById("receiptFile")?.click());
document.getElementById("receiptCameraInput")?.addEventListener("change",e=>{if(e.target.files?.[0])reviewFile(e.target.files[0]);});
document.getElementById("receiptFile")?.addEventListener("change",e=>{if(e.target.files?.[0])reviewFile(e.target.files[0]);});
document.getElementById("cancelReceiptBtn")?.addEventListener("click",()=>{currentReceiptFile=null;document.getElementById("receiptReview")?.classList.add("hidden");});
document.getElementById("receiptReviewForm")?.addEventListener("submit",async e=>{e.preventDefault();if(!sb||!currentReceiptFile){alert("Bitte zuerst einen Beleg auswählen.");return;}const datum=document.getElementById("receiptDate").value||new Date().toISOString().slice(0,10),net=Number(document.getElementById("receiptNet").value||0),vat=Number(document.getElementById("receiptVat").value||0),gross=Number(document.getElementById("receiptGross").value||0);if(gross<=0){alert("Bitte einen Bruttobetrag eingeben.");return;}const supplier=document.getElementById("receiptSupplier").value.trim(),desc=document.getElementById("receiptDescription").value.trim()||supplier||"Beleg",invoice=document.getElementById("receiptInvoiceNumber").value.trim(),cat=document.getElementById("receiptCategory").value;const row={datum,lieferant:supplier||null,rechnungsnummer:invoice||null,beschreibung:desc,netto:net,mwst:vat,brutto:gross,betrag:gross,kategorie:cat,dateiname:currentReceiptFile.name,mime_type:currentReceiptFile.type||null};setText("receiptUploadStatus","Speichere…");const{error}=await sb.from("belege").insert(row);if(error){setText("receiptUploadStatus","Fehler: "+error.message);return;}const ex=await sb.from("ausgaben").insert({datum,beschreibung:desc,betrag:gross,netto:net,mwst:vat,brutto:gross,kategorie:cat,quelle:currentReceiptFile.name,rechnungsnummer:invoice||null});setText("receiptUploadStatus",ex.error?"Beleg gespeichert; Ausgabe konnte nicht gespeichert werden.":"Beleg und Ausgabe erfolgreich gespeichert.");await loadData();});
init();